---
title: "Project Draft"
output: html_document
date: "2025-11-21"
author: Will Deley, Anish Mantri, Alexander Teran
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(dplyr)
```



```{r, include=FALSE}
nba_24_25_playoff_shooting_data <- read_csv("./nba_24-25_playoff_shooting_by_zone.csv")
nba_24_25_playoff_shooting_data
```


```{r, include=FALSE}
nba_24_25_playoff_team_data <- read_csv("./nba_24-25_playoff_team_statistics.csv")
nba_24_25_playoff_team_data
```


# need to clean up the data - convert cols into numeric types before we can do this
```{r}
nba_24_25_playoff_shooting_data <- nba_24_25_playoff_shooting_data %>%
  mutate(across(
    c(`Restricted Area FGM`, `Restricted Area FGA`,
      `In The Paint (Non-RA) FGM`, `In The Paint (Non-RA) FGA`,
      `Mid-Range FGM`, `Mid-Range FGA`,
      `Corner 3 FGM`, `Corner 3 FGA`,
      `Above the Break 3. FGM`, `Above the Break 3. FGA`),
    ~ as.numeric(.)
  )) %>%
  mutate(
    `3 FGM` = `Corner 3 FGM` + `Above the Break 3. FGM`,
    `3 FGA` = `Corner 3 FGA` + `Above the Break 3. FGA`,
    `3 FG%` = ifelse(`3 FGA` == 0, 0, (`3 FGM` / `3 FGA`) * 100),
    `2 FGM` = `Restricted Area FGM` + `In The Paint (Non-RA) FGM` + `Mid-Range FGM`,
    `2 FGA` = `Restricted Area FGA` + `In The Paint (Non-RA) FGA` + `Mid-Range FGA`,
    `2 FG%` = ifelse(`2 FGA` == 0, 0, (`2 FGM` / `2 FGA`) * 100)
  )

```

## Introduction - Anish


## Background - Will


## Analysis - Group


```{r}
```

```{r}
nba_summary <- nba_24_25_playoff_shooting_data %>%
  group_by(Team) %>%
  summarise(
    total_3FGA = sum(`3 FGA`),
    total_2FGA = sum(`2 FGA`)
  ) %>%
  full_join(
    nba_24_25_playoff_team_data %>% select(Team, `WIN%`),
    by = "Team"
  )

nba_summary %>%
  mutate(`3_2_pointDifference` = total_2FGA - total_3FGA) %>%
  ggplot(aes(x = `3_2_pointDifference`, y = `WIN%`, color = Team)) +
  geom_smooth(aes(group = 1), method = "lm", color = "black", se = FALSE) +
  geom_point(aes(size = total_3FGA), alpha = 0.7 ) +
  labs(
    x = "2pt FGA - 3pt FGA",
    y = "Win Percentage",
    title = "Impact of 2-pt vs 3-pt Attempts on Playoff Win %"
  )


```

## Discussion - Alexander


## Reference
